### ISSUE TITLE
Bloom Perspective not allowing DB Switch

### ISSUE THREAD

**Issue by palmergw** [neo4j-apps/neo4j-bloom#58]
I am running into an issue with Bloom not connecting to Databases running a local instance of Neo4j Desktop 1.5.8, on a 5.8.0 DB using ports 7687 and 7474.
I had just installed a new version of the Bloom app.

I tried forcing a reinstall of Bloom, but that didn't change anything.
Sometimes Bloom will load the default database no problem, and usually if I reload Bloom it will tell me that there is no active DB. I can't find errors on the Neo4j Desktop side. When it does load, under perspectives it behaves normally for the default DB, but I cannot switch to my other DB.

I also spun up a new 5.8.0 DBMS to test there, same results.

Message in Bloom after a reload:

> We couldn't find an active graph in Neo4j Desktop. Please check that you have connected to a graph.

Neo4j Browser does not display this behavior, allows switching between the default 'neo4j' and other databases without issue.

**Comment by palmergw** [comment]
Recurring events in logs which may be related:

security.log:
```
2023-05-25 18:46:47.504+0000 INFO  {plugin-com.neo4j.plugin.jwt.auth.JwtAuthPlugin} Log in attempted for user 'neo4j'.
2023-05-25 18:46:47.504+0000 ERROR {plugin-com.neo4j.plugin.jwt.auth.JwtAuthPlugin} Invalid serialized unsecured/JWS/JWE object: Missing part delimiters
2023-05-25 18:46:47.504+0000 INFO  [neo4j]: logged in
```

debug.log:
```
2023-05-25 18:47:17.179+0000 WARN  [i.n.c.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
org.neo4j.bolt.runtime.BoltConnectionFatality: Terminated connection 'bolt-52' ([id: 0xd65fb4cc, L:/127.0.0.1:7687 ! R:/127.0.0.1:56852]) as the client failed to authenticate within 30000 ms.
	at org.neo4j.bolt.protocol.common.handler.AuthenticationTimeoutHandler.authTimerEnded(AuthenticationTimeoutHandler.java:91) ~[neo4j-bolt-5.8.0.jar:5.8.0]
	at org.neo4j.bolt.protocol.common.handler.AuthenticationTimeoutHandler.lambda$handlerAdded$0(AuthenticationTimeoutHandler.java:59) ~[neo4j-bolt-5.8.0.jar:5.8.0]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) [netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) [netty-transport-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.92.Final.jar:4.1.92.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.92.Final.jar:4.1.92.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by MahesGuru07** [comment]
Hai,
Sorry for the inconvenience, Could you please verify it happens only after upgrading to 2.8.0 ? 
You can verify through About section in Bloom.
If yes, it's a known issue. It will be fixed in upcoming patch release within this week.
Thank you for reporting.

**Comment by palmergw** [comment]
I'd be happy to validate. I haven't found a way to roll Bloom back to a previous version.
When I uninstall/reinstall Neo4j, it installs Bloom to the latest version.

Looking under the About section does show Bloom as version 2.8.0.

**Comment by palmergw** [comment]
Updating to 2.8.1 resolved this issue.

Thank you!
